### ISSUE TITLE
Add Compatibility for SSR

### ISSUE THREAD

**Issue by austinheinrichs** [cloudflare/stream-angular#2] opened 2020-06-08 16:35 UTC
Adding issue for SSR compatibility - not sure if you want to look at this one.  Please let me know if you would like me to add a repro on this and I can put one together.  There are references to window and document that throw errors when run server side.  If you check the platform and load the component after the browser transition, the player doesn't work correctly.

**Comment by selected-pixel-jameson** [comment] 2022-01-06 01:02
Apparently this is not a concern.

**Comment by third774** [comment] 2022-04-07 18:21
Hey, y'all! Taking a look at this now, and I'm able to reproduce the issue. Working out how best to solve this in our package, and happy to discuss ideas/approaches. In the meantime, it looks like (based on my local testing, at least) you might be able to conditionally only render it in the browser:

`app.component.tsx`
```tsx
import { isPlatformBrowser } from '@angular/common';
import { Component, Inject, PLATFORM_ID } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'angular-starter';
  version = 'Angular version 13.3.0';
  constructor(@Inject(PLATFORM_ID) private platformId: any) {}
  get isBrowser() {
    return isPlatformBrowser(this.platformId);
  }
}
```

`app.component.html`
```html
<main>
  <cloudflare-stream
    *ngIf="isBrowser"
    [controls]="true"
    src="644822f93dcddab3e9441587d184ca2f"
  ></cloudflare-stream>
</main>
```

**Comment by third774** [comment] 2022-04-08 14:14
Hey y'all — I've just published a release candidate build under the `next` tag. Can you try this out and let me know if it is working as expected for you?

`npm i @cloudflare/stream-angular@next`

**Comment by austinheinrichs** [comment] 2022-04-26 12:08
@third774 thank you for resolving this.  I will try to test this out sometime this week.  I had tried the workaround you mentioned above (https://github.com/cloudflare/stream-angular/issues/2#issuecomment-1092065479), but the player itself didn't function properly after the transition to the browser.

**Comment by third774** [comment] 2022-05-16 18:34
Gonna close this for now assuming that this works — please let me know if you run into any issues!

**Closed by third774** 2022-05-16 18:34 UTC
